"""탐지 설명표 — 팀이 쓴 한글 설명(문제 / 왜 위험 / 고치는 법 / 고치는 곳 / 관련 SEC).

AWS 원문(Description·Remediation)과 따로 둔다. 화면은 둘을 구분해 보여준다(용어집 1장 원본 값 보존).
자동 조치 여부는 여기 쓰지 않는다 — 설정(AUTO_REMEDIABLE_*)에 따라 바뀌므로 guidance.AutoPolicy 가 계산한다.

키
  - Security Hub 규칙 ID (AWS Foundational Security Best Practices, 이 프로젝트가 켠 유일한 표준)
  - GuardDuty 유형 원래 형식 (Security Hub 가 "/" 를 "-" 로 바꿔 넣어도 guidance.py 가 되돌려 찾는다)
  - "config:<규칙 이름 끝>" — 이 프로젝트 Config 규칙 4개 (modules/security/config.tf)
  - "waf:soar-waf-alarm" — WAF 차단 알람을 가져온 finding (modules/soar/lambda_src/waf_finding)
  - "product:<ProductName>" — 규칙 ID 가 없는 제품의 공통 설명
  - "family:<위협 목적>" — 표에 없는 GuardDuty 유형의 공통 설명
항목을 늘릴 때는 우리 계정에 실제로 뜨는 탐지부터 넣는다. 문장은 짧게, 이 프로젝트 기준으로 쓴다.
"""

# 고치는 곳 — 이 프로젝트에서 누가·어디서 고치는지(Terraform 소유 경계, terraform/docs/OWNERSHIP.md).
WHERE = {
    "terraform": "Terraform — 코드 수정 후 plan·apply (콘솔에서 고치면 다음 apply 가 되돌림)",
    "sg": "보안그룹 규칙 — Terraform 이 만든 규칙은 코드에서, 수동으로 만든 규칙은 콘솔에서 삭제",
    "iam": "IAM 정책 — Terraform 정책은 코드에서, 수동 정책은 콘솔에서 수정",
    "iam-user": "IAM 사용자 — 콘솔에서 사용자별로 조치 (Terraform 이 관리하지 않음)",
    "account": "계정·리전 설정 — 콘솔·CLI 로 한 번 설정 (Terraform 이 관리하지 않음)",
    "patch": "서버 패치 — 패키지 업데이트, 커널이면 재부팅 필요",
    "investigate": "사람 확인 — 공격인지·영향이 있는지 조사한 뒤 조치",
}


def _e(title, problem, risk, fix, where, scenario=None, note=None):
    return {"title": title, "problem": problem, "risk": risk, "fix": list(fix), "where": where,
            "scenario": scenario, "note": note}


CONTROLS = {
    # --- EC2 · 네트워크 ---------------------------------------------------------------
    "EC2.2": _e("VPC 기본 보안그룹에 규칙이 남아 있음",
                "기본 보안그룹(default)이 트래픽을 허용합니다.",
                "보안그룹을 지정하지 않고 만든 자원이 자동으로 이 그룹에 들어가 의도하지 않은 통신이 열립니다.",
                ["기본 보안그룹의 인바운드·아웃바운드 규칙 모두 삭제", "자원마다 용도별 전용 보안그룹 사용"],
                "account", note="프로젝트 VPC 의 기본 보안그룹만 자동 조치합니다. 다른 VPC(계정 기본 VPC 등)는 수동입니다."),
    "EC2.3": _e("연결된 EBS 볼륨이 암호화되지 않음",
                "인스턴스에 붙은 EBS 볼륨이 평문으로 저장됩니다.",
                "스냅샷이나 디스크가 유출되면 데이터가 그대로 노출됩니다.",
                ["기존 볼륨은 바로 암호화할 수 없음 — 암호화된 스냅샷 복사본으로 새 볼륨을 만들어 교체",
                 "Terraform 인스턴스는 root_block_device encrypted = true (이 프로젝트 기본값)"],
                "terraform"),
    "EC2.4": _e("오래 중지된 EC2 인스턴스",
                "중지된 채로 오래 남은 인스턴스가 있습니다.",
                "패치되지 않은 상태로 남아 있다가 다시 켜지면 취약한 채로 운영됩니다.",
                ["필요 없으면 종료 (Terraform 자원이면 코드에서 제거하거나 enable 변수 false)"],
                "terraform"),
    "EC2.6": _e("VPC 흐름 로그(Flow Logs) 꺼짐",
                "VPC 에 흐름 로그가 설정되어 있지 않습니다.",
                "어떤 IP 가 어느 포트로 접속했고 허용·거부됐는지 기록이 없어 공격 추적과 SSH 거부 급증 탐지(SEC-06B)를 할 수 없습니다.",
                ["enable_flow_logs = true 로 흐름 로그를 CloudWatch Logs 에 보냄"],
                "terraform", "SEC-09"),
    "EC2.7": _e("EBS 기본 암호화 꺼짐",
                "리전의 EBS 기본 암호화 설정이 꺼져 있습니다.",
                "암호화 옵션을 빠뜨리고 만든 볼륨·스냅샷이 평문으로 저장됩니다.",
                ["EC2 설정에서 EBS 기본 암호화 켜기 — 새로 만드는 볼륨부터 적용, 기존 볼륨은 그대로"],
                "account", note="이 프로젝트 EC2 루트 볼륨은 Terraform 에서 이미 암호화(encrypted = true)되어 있습니다."),
    "EC2.8": _e("IMDSv2 강제 안 됨",
                "인스턴스 메타데이터 서비스가 토큰 없는 v1 요청을 받습니다.",
                "웹 취약점(SSRF)으로 메타데이터에 접근해 인스턴스 역할 자격 증명을 빼낼 수 있습니다.",
                ["metadata_options 의 http_tokens = \"required\""],
                "terraform", note="이 프로젝트 Terraform 인스턴스는 required 로 설정되어 있습니다. Terraform 밖에서 만든 인스턴스인지 확인하세요."),
    "EC2.9": _e("EC2 인스턴스에 공인 IPv4 주소",
                "인스턴스에 공인 IP 가 붙어 있습니다.",
                "보안그룹 설정 실수 하나로 인터넷에서 바로 접근됩니다.",
                ["외부 공개가 필요 없으면 사설 서브넷에 두고 ALB·SSM Session Manager 로 접근",
                 "공개가 필요한 실습 대상(DVWA 등)은 목적을 기록하고 보안그룹을 최소화"],
                "terraform"),
    "EC2.10": _e("EC2 API 용 VPC 엔드포인트 없음",
                 "사설 서브넷 인스턴스의 EC2 API 호출이 인터넷(NAT) 경로로 나갑니다.",
                 "AWS API 트래픽이 인터넷 경로를 타고, NAT 가 없으면 호출이 실패합니다.",
                 ["ec2 인터페이스 VPC 엔드포인트 추가 (시간당 비용 발생)"],
                 "terraform"),
    "EC2.13": _e("보안그룹이 인터넷에 SSH(22) 허용",
                 "0.0.0.0/0 에서 22번으로 들어오는 규칙이 있습니다.",
                 "SSH 무차별 대입 공격 대상이 됩니다.",
                 ["22번 공개 규칙 삭제, 접속은 SSM Session Manager 사용", "꼭 필요하면 관리자 IP(/32)만 허용"],
                 "sg", "SEC-01"),
    "EC2.14": _e("보안그룹이 인터넷에 RDP(3389) 허용",
                 "0.0.0.0/0 에서 3389번으로 들어오는 규칙이 있습니다.",
                 "원격 데스크톱 무차별 대입 공격 대상이 됩니다.",
                 ["3389번 공개 규칙 삭제"],
                 "sg", "SEC-01"),
    "EC2.15": _e("서브넷이 공인 IP 를 자동 할당",
                 "이 서브넷에 만든 인스턴스가 자동으로 공인 IP 를 받습니다.",
                 "공개할 생각이 없던 인스턴스도 인터넷에 노출됩니다.",
                 ["map_public_ip_on_launch = false, 공인 IP 가 필요한 인스턴스만 명시적으로 할당"],
                 "terraform"),
    "EC2.18": _e("보안그룹이 허가되지 않은 포트를 인터넷에 공개",
                 "허가된 포트(기본 80·443) 밖의 포트가 0.0.0.0/0 에 열려 있습니다.",
                 "의도하지 않은 서비스가 인터넷에 노출됩니다.",
                 ["불필요한 공개 규칙 삭제 또는 출발지를 필요한 대역으로 좁힘"],
                 "sg", "SEC-01·SEC-03"),
    "EC2.19": _e("보안그룹이 위험 포트를 인터넷에 공개",
                 "22·3306·3389 같은 고위험 포트가 0.0.0.0/0 에 열려 있습니다.",
                 "DB·원격 접속 포트가 인터넷 스캔과 무차별 대입에 노출됩니다.",
                 ["공개 규칙 삭제, DB 포트는 앱 서버 보안그룹에서만 허용"],
                 "sg", "SEC-01·SEC-03",
                 note="AutoRemediation=enabled 태그가 있는 보안그룹(db-auto-sg)만 자동 회수하고, 태그 없는 db-manual-sg 는 대조군으로 수동 처리합니다."),
    "EC2.21": _e("네트워크 ACL 이 인터넷에 22·3389 허용",
                 "NACL 이 0.0.0.0/0 에서 22 또는 3389 인바운드를 허용합니다.",
                 "보안그룹 한 겹만 남아 설정 실수가 곧바로 노출로 이어집니다.",
                 ["NACL 규칙(100번 이상, Terraform 소유)에서 22·3389 허용 제거", "1~99번은 SOAR 차단 전용이라 코드에 넣지 않음"],
                 "terraform", "SEC-01"),
    "EC2.22": _e("사용하지 않는 보안그룹",
                 "어느 자원에도 연결되지 않은 보안그룹이 있습니다.",
                 "관리되지 않는 규칙이 쌓여 나중에 잘못 연결될 수 있습니다.",
                 ["Terraform 이 만든 그룹이면 코드에서 제거, 수동으로 만든 그룹이면 콘솔에서 삭제"],
                 "sg"),
    "EC2.28": _e("EBS 볼륨이 백업 계획에 없음",
                 "EBS 볼륨이 AWS Backup 계획에 들어 있지 않습니다.",
                 "장애나 실수로 지웠을 때 복구할 지점이 없습니다.",
                 ["AWS Backup 계획에 볼륨 포함 (백업 저장 비용 발생)"],
                 "terraform"),
    "EC2.53": _e("보안그룹이 인터넷(IPv4)에 원격 관리 포트 허용",
                 "0.0.0.0/0 에서 22 또는 3389 로 들어오는 규칙이 있습니다.",
                 "원격 접속 포트가 무차별 대입에 노출됩니다.",
                 ["22·3389 공개 규칙 삭제, 접속은 SSM Session Manager 사용"],
                 "sg", "SEC-01",
                 note="같은 규칙이 EC2.19 로도 탐지되면 EC2.19 자동 조치(태그 조건)에서 함께 회수됩니다."),
    "EC2.54": _e("보안그룹이 인터넷(IPv6)에 원격 관리 포트 허용",
                 "::/0 에서 22 또는 3389 로 들어오는 규칙이 있습니다.",
                 "원격 접속 포트가 IPv6 인터넷에 노출됩니다.",
                 ["::/0 공개 규칙 삭제"],
                 "sg", "SEC-01"),
    "EC2.182": _e("EBS 스냅샷 퍼블릭 액세스 차단 꺼짐",
                  "리전 설정이 EBS 스냅샷의 공개 공유를 막지 않습니다.",
                  "스냅샷을 실수로 공개하면 디스크 내용 전체가 누구에게나 노출됩니다.",
                  ["EC2 설정에서 스냅샷 퍼블릭 액세스 차단을 '모든 공유 차단'으로 설정"],
                  "account"),
    # --- S3 ------------------------------------------------------------------------------
    "S3.1": _e("S3 계정 수준 퍼블릭 액세스 차단 꺼짐",
               "계정 전체의 S3 퍼블릭 액세스 차단 설정 4개가 모두 켜져 있지 않습니다.",
               "버킷 하나의 정책·ACL 실수로 데이터가 인터넷에 공개될 수 있습니다.",
               ["S3 > 이 계정의 퍼블릭 액세스 차단 설정 4개 모두 켜기"],
               "account"),
    "S3.5": _e("S3 버킷이 HTTPS 요청만 허용하지 않음",
               "버킷 정책이 평문 HTTP 요청을 거부하지 않습니다.",
               "전송 중인 데이터가 노출될 수 있습니다.",
               ["버킷 정책에 aws:SecureTransport = false 요청 거부(Deny) 추가"],
               "terraform"),
    "S3.8": _e("S3 버킷 퍼블릭 액세스 차단 꺼짐",
               "버킷 수준 퍼블릭 액세스 차단 설정이 모두 켜져 있지 않습니다.",
               "버킷 정책·ACL 변경만으로 버킷이 공개될 수 있습니다.",
               ["aws_s3_bucket_public_access_block 네 항목 모두 true"],
               "terraform"),
    "S3.9": _e("S3 서버 액세스 로깅 꺼짐",
               "버킷 접근 기록이 남지 않습니다.",
               "누가 어떤 객체에 접근했는지 알 수 없어 유출 조사가 어렵습니다.",
               ["로그 전용 버킷을 만들고 서버 액세스 로깅 대상으로 지정 (저장 비용 발생)"],
               "terraform", "SEC-09"),
    "S3.13": _e("S3 수명 주기 정책 없음",
                "오래된 객체·버전을 정리하는 규칙이 없습니다.",
                "데이터가 계속 쌓여 비용과 노출 범위가 커집니다.",
                ["aws_s3_bucket_lifecycle_configuration 으로 만료 규칙 추가"],
                "terraform"),
    # --- IAM -----------------------------------------------------------------------------
    "IAM.1": _e("관리자 전체 권한(*:*) 정책",
                "Action \"*\" · Resource \"*\" 를 허용하는 고객 관리형 정책이 있습니다.",
                "이 정책이 붙은 사용자·역할이 탈취되면 계정 전체가 넘어갑니다.",
                ["필요한 작업·자원만 허용하도록 정책 축소"],
                "iam", "SEC-05"),
    "IAM.2": _e("IAM 사용자에 정책을 직접 연결",
                "정책이 그룹이 아니라 사용자에게 직접 붙어 있습니다.",
                "권한이 사람마다 흩어져 검토·회수가 어렵습니다.",
                ["정책은 그룹에 붙이고 사용자는 그룹에 추가"],
                "iam-user", "SEC-05"),
    "IAM.3": _e("액세스 키를 90일 넘게 교체하지 않음",
                "90일 넘게 같은 액세스 키를 쓰고 있습니다.",
                "오래된 키일수록 어딘가에 유출됐을 가능성이 커집니다.",
                ["새 키 발급 → 사용처 교체 → 옛 키 비활성화·삭제", "가능하면 액세스 키 대신 역할·SSO 사용"],
                "iam-user", "SEC-05"),
    "IAM.4": _e("루트 계정 액세스 키 존재",
                "루트 사용자에게 액세스 키가 있습니다.",
                "루트 키는 권한을 제한할 수 없어 유출되면 계정 전체가 넘어갑니다.",
                ["루트로 로그인 → 보안 자격 증명 → 액세스 키 삭제"],
                "account"),
    "IAM.5": _e("콘솔 비밀번호 사용자에 MFA 없음",
                "콘솔 비밀번호가 있는 IAM 사용자가 MFA 를 쓰지 않습니다.",
                "비밀번호만 유출돼도 콘솔에 로그인됩니다.",
                ["해당 사용자가 로그인해 보안 자격 증명에서 MFA 장치 등록"],
                "iam-user", "SEC-05"),
    "IAM.6": _e("루트 계정 하드웨어 MFA 없음",
                "루트 사용자에 하드웨어 MFA 가 없습니다.",
                "계정 최고 권한의 보호가 약합니다.",
                ["루트에 하드웨어 MFA 등록 (가상 MFA 만 있으면 이 규칙은 계속 실패로 남음)"],
                "account"),
    "IAM.7": _e("IAM 비밀번호 정책이 약함",
                "계정 비밀번호 정책이 없거나 길이·문자 조건이 기준보다 약합니다.",
                "추측·무차별 대입으로 콘솔 비밀번호가 뚫리기 쉽습니다.",
                ["최소 8자, 대문자·소문자·숫자·기호 모두 요구"],
                "account", note="기존 값이 더 엄격하면 그대로 둡니다. 기존 사용자 비밀번호는 바로 만료되지 않습니다."),
    "IAM.8": _e("90일 넘게 쓰지 않은 자격 증명",
                "오래 쓰지 않은 비밀번호나 액세스 키가 남아 있습니다.",
                "주인 없는 자격 증명이 탈취 경로로 남습니다.",
                ["쓰지 않는 비밀번호·액세스 키 비활성화 또는 삭제"],
                "iam-user", "SEC-05"),
    "IAM.9": _e("루트 계정 MFA 없음",
                "루트 사용자가 MFA 를 쓰지 않습니다.",
                "루트 비밀번호만으로 계정 전체에 로그인됩니다.",
                ["루트 계정에 MFA 등록"],
                "account"),
    "IAM.21": _e("정책이 서비스 전체 권한(서비스:*) 허용",
                 "고객 관리형 정책에 \"s3:*\" 같은 와일드카드 작업이 있습니다.",
                 "필요 이상 권한이 있어 탈취되면 피해가 커집니다.",
                 ["와일드카드를 실제로 쓰는 작업 목록으로 교체"],
                 "iam", "SEC-05"),
    # --- 로깅·탐지 서비스 ----------------------------------------------------------------
    "CloudTrail.1": _e("다중 리전 CloudTrail 없음",
                       "모든 리전의 읽기·쓰기 관리 이벤트를 기록하는 추적이 없습니다.",
                       "API 호출 기록이 빠져 사고 조사를 할 수 없습니다.",
                       ["모든 리전·읽기/쓰기 관리 이벤트를 기록하는 추적 유지 (aws_cloudtrail)"],
                       "terraform", "SEC-09"),
    "CloudTrail.2": _e("CloudTrail 로그 KMS 암호화 안 됨",
                       "CloudTrail 로그가 KMS 키로 암호화되지 않습니다.",
                       "로그 버킷 접근 권한만으로 로그 내용을 읽을 수 있습니다.",
                       ["aws_cloudtrail 의 kms_key_id 지정"],
                       "terraform", "SEC-09"),
    "CloudTrail.4": _e("CloudTrail 로그 파일 무결성 검증 꺼짐",
                       "로그 파일 변조를 확인하는 다이제스트가 만들어지지 않습니다.",
                       "로그가 바뀌거나 지워져도 알 수 없습니다.",
                       ["enable_log_file_validation = true"],
                       "terraform", "SEC-09"),
    "CloudTrail.5": _e("CloudTrail 이 CloudWatch Logs 로 가지 않음",
                       "CloudTrail 이벤트가 CloudWatch Logs 로 전달되지 않습니다.",
                       "API 호출을 실시간 지표·알람으로 볼 수 없습니다.",
                       ["cloud_watch_logs_group_arn·역할 설정 (로그 저장 비용 발생)"],
                       "terraform", "SEC-09"),
    "Config.1": _e("AWS Config 기록 범위 부족",
                   "Config 가 꺼져 있거나, Security Hub 규칙에 필요한 자원 유형을 모두 기록하지 않습니다.",
                   "설정 변경 이력이 남지 않고 일부 점검 규칙이 평가되지 않습니다.",
                   ["Config 기록기가 필요한 자원 유형을 모두 기록하도록 설정 (기록량만큼 비용 발생)"],
                   "terraform", "SEC-09", note="이 프로젝트는 비용 때문에 Config 기록 유형을 줄여 두었습니다."),
    "GuardDuty.1": _e("GuardDuty 꺼짐",
                      "이 리전에서 GuardDuty 가 켜져 있지 않습니다.",
                      "무차별 대입·자격 증명 유출 같은 위협을 탐지하지 못합니다.",
                      ["GuardDuty 탐지기 켜기 (aws_guardduty_detector)"],
                      "terraform"),
    "Inspector.1": _e("Inspector EC2 스캔 꺼짐",
                      "Inspector 가 EC2 인스턴스를 스캔하지 않습니다.",
                      "서버 패키지의 알려진 취약점(CVE)을 찾지 못합니다.",
                      ["aws_inspector2_enabler 에 EC2 포함"],
                      "terraform", "SEC-04"),
    "Inspector.2": _e("Inspector ECR 스캔 꺼짐",
                      "Inspector 가 ECR 컨테이너 이미지를 스캔하지 않습니다.",
                      "이미지의 알려진 취약점(CVE)을 찾지 못합니다.",
                      ["aws_inspector2_enabler 에 ECR 포함"],
                      "terraform", "SEC-04"),
    # --- Systems Manager -----------------------------------------------------------------
    "SSM.1": _e("EC2 가 Systems Manager 관리 대상이 아님",
                "인스턴스가 SSM 에 등록되지 않았습니다.",
                "패치·명령 실행·세션 접속(SSH 대체)을 SSM 으로 할 수 없습니다.",
                ["인스턴스 프로파일에 AmazonSSMManagedInstanceCore", "SSM 에이전트 실행과 SSM 엔드포인트(또는 NAT) 경로 확인"],
                "terraform"),
    "SSM.2": _e("SSM 패치 준수 실패",
                "적용되지 않은 패치가 있습니다.",
                "알려진 취약점(CVE)이 고쳐지지 않은 채 남아 있습니다.",
                ["패치 적용 — 커널 패치는 재부팅이 필요하므로 시연 일정 확인", "취약점 점검 탭에서 패키지별 목록 확인"],
                "patch", "SEC-04"),
    "SSM.3": _e("SSM 연결(Association) 준수 실패",
                "State Manager 연결 실행이 실패했습니다.",
                "원하는 설정이 인스턴스에 적용되지 않은 상태입니다.",
                ["실패한 연결의 실행 기록을 확인하고 원인 해결 후 다시 실행"],
                "account"),
    "SSM.4": _e("SSM 문서가 공개됨",
                "SSM 문서가 모든 계정에 공유되어 있습니다.",
                "문서 안의 스크립트·설정이 외부에 노출됩니다.",
                ["문서 공유 권한에서 All(공개) 제거"],
                "terraform"),
    "SSM.6": _e("SSM Automation 스크립트 로그 꺼짐",
                "Automation 문서의 스크립트 실행 로그가 CloudWatch Logs 로 가지 않습니다.",
                "자동 조치 스크립트가 무엇을 했는지 추적할 수 없습니다.",
                ["Systems Manager 설정에서 스크립트 로그 대상을 CloudWatch 로 지정"],
                "account"),
    "SSM.7": _e("SSM 문서 공개 공유 차단 꺼짐",
                "계정 설정이 SSM 문서의 공개 공유를 막지 않습니다.",
                "문서를 실수로 공개할 수 있습니다.",
                ["Systems Manager > 문서 > 기본 설정에서 공개 공유 차단 켜기"],
                "account"),
    # --- ALB · Lambda · 데이터 ----------------------------------------------------------
    "ELB.1": _e("ALB 가 HTTP 를 HTTPS 로 리디렉션하지 않음",
                "80번(HTTP) 요청을 443번(HTTPS)으로 넘기지 않습니다.",
                "로그인 정보 같은 데이터가 평문으로 오갑니다.",
                ["ACM 인증서 발급 → 443 리스너 추가 → 80 리스너를 443 리디렉션으로 변경"],
                "terraform", "SEC-02", note="도메인과 인증서가 없으면 적용할 수 없습니다."),
    "ELB.4": _e("ALB 가 잘못된 HTTP 헤더를 버리지 않음",
                "형식이 잘못된 헤더가 백엔드까지 전달됩니다.",
                "요청 밀반입(HTTP desync) 공격에 쓰일 수 있습니다.",
                ["drop_invalid_header_fields = true"],
                "terraform", "SEC-02"),
    "ELB.5": _e("ALB 액세스 로그 꺼짐",
                "로드밸런서 요청 기록이 남지 않습니다.",
                "웹 공격 요청을 나중에 추적할 수 없습니다.",
                ["access_logs 로 S3 저장 (버킷 정책에 ELB 쓰기 권한 필요)"],
                "terraform", "SEC-09"),
    "ELB.6": _e("ALB 삭제 보호 꺼짐",
                "로드밸런서 삭제 보호가 꺼져 있습니다.",
                "실수나 악의로 로드밸런서가 바로 삭제됩니다.",
                ["enable_deletion_protection = true (켜면 terraform destroy 전에 먼저 꺼야 함)"],
                "terraform"),
    "Lambda.1": _e("Lambda 함수가 공개 호출을 허용",
                   "함수 정책이 누구나 호출할 수 있게 되어 있습니다.",
                   "외부에서 함수를 마음대로 실행할 수 있습니다.",
                   ["aws_lambda_permission 에 source_arn·source_account 조건 지정"],
                   "terraform"),
    "Lambda.2": _e("지원이 끝나는 Lambda 런타임",
                   "지원 종료됐거나 곧 종료되는 런타임을 씁니다.",
                   "보안 패치가 끊긴 환경에서 코드가 실행됩니다.",
                   ["runtime 을 지원 버전으로 올리고 테스트"],
                   "terraform"),
    "DynamoDB.2": _e("DynamoDB 특정 시점 복구(PITR) 꺼짐",
                     "테이블의 특정 시점 복구가 꺼져 있습니다.",
                     "실수로 지우거나 덮어쓴 데이터를 되돌릴 수 없습니다.",
                     ["point_in_time_recovery enabled = true (저장 비용 발생)"],
                     "terraform"),
    "DynamoDB.6": _e("DynamoDB 삭제 보호 꺼짐",
                     "테이블 삭제 보호가 꺼져 있습니다.",
                     "테이블이 실수로 바로 삭제될 수 있습니다.",
                     ["deletion_protection_enabled = true (켜면 terraform destroy 전에 먼저 꺼야 함)"],
                     "terraform"),
    "KMS.4": _e("KMS 키 자동 교체 꺼짐",
                "고객 관리형 KMS 키의 자동 교체가 꺼져 있습니다.",
                "같은 키 재료를 오래 쓰면 유출 시 영향 범위가 커집니다.",
                ["enable_key_rotation = true"],
                "terraform"),
    "SQS.1": _e("SQS 대기열 암호화 안 됨",
                "대기열 메시지가 저장 시 암호화되지 않습니다.",
                "대기열 접근 권한만으로 메시지 내용을 읽을 수 있습니다.",
                ["sqs_managed_sse_enabled = true 또는 KMS 키 지정"],
                "terraform"),
    "SecretsManager.1": _e("Secrets Manager 자동 교체 꺼짐",
                           "비밀 값의 자동 교체가 설정되어 있지 않습니다.",
                           "유출된 비밀번호가 계속 유효합니다.",
                           ["교체 Lambda 로 자동 교체 설정, 또는 ASR-RotateDbSecret 수동 교체 절차 운영"],
                           "terraform", "SEC-07"),
    "ECR.1": _e("ECR 푸시 시 이미지 스캔 꺼짐",
                "이미지를 올릴 때 취약점 스캔을 하지 않습니다.",
                "취약한 이미지가 검사 없이 배포될 수 있습니다.",
                ["scan_on_push = true 또는 Inspector 향상된 스캔 사용"],
                "terraform", "SEC-04"),
    "ECR.2": _e("ECR 이미지 태그 변경 가능",
                "같은 태그로 다른 이미지를 덮어쓸 수 있습니다.",
                "검증하지 않은 이미지가 같은 태그로 배포될 수 있습니다.",
                ["image_tag_mutability = \"IMMUTABLE\""],
                "terraform", "SEC-04"),
    "ECR.3": _e("ECR 수명 주기 정책 없음",
                "오래된 이미지를 정리하는 규칙이 없습니다.",
                "취약한 옛 이미지가 계속 남아 실수로 배포될 수 있습니다.",
                ["aws_ecr_lifecycle_policy 로 보관 개수 제한"],
                "terraform", "SEC-04"),
    "Account.1": _e("계정 보안 연락처 없음",
                    "AWS 계정에 보안 담당 연락처가 등록되어 있지 않습니다.",
                    "AWS 가 보안 문제를 알릴 담당자가 없습니다.",
                    ["계정 설정 > 대체 연락처 > 보안 연락처 등록"],
                    "account"),
}

GUARDDUTY = {
    "UnauthorizedAccess:EC2/SSHBruteForce": _e(
        "SSH 무차별 대입",
        "EC2 가 SSH 무차별 대입에 관여했습니다(공격 대상이거나 공격 출발지).",
        "대상이면 계정 탈취 시도, 출발지면 인스턴스가 이미 침해됐을 수 있습니다.",
        ["22번을 인터넷에 열지 않기 (접속은 SSM)", "대상이면 공격 IP 차단(NACL), 출발지면 인스턴스 격리·조사"],
        "investigate", "SEC-06B",
        note="SSH 공격 IP 자동 차단은 GuardDuty 가 아니라 Flow Logs 22번 거부 알람 경로(SEC-06B)로 동작합니다."),
    "UnauthorizedAccess:EC2/RDPBruteForce": _e(
        "RDP 무차별 대입",
        "EC2 가 원격 데스크톱(3389) 무차별 대입에 관여했습니다.",
        "대상이면 계정 탈취 시도, 출발지면 인스턴스가 이미 침해됐을 수 있습니다.",
        ["3389번 공개 규칙 삭제", "출발지면 인스턴스 격리·조사"],
        "investigate"),
    "Recon:EC2/PortProbeUnprotectedPort": _e(
        "보호되지 않은 포트 탐색",
        "인터넷의 알려진 스캐너가 이 인스턴스의 열린 포트를 탐색했습니다.",
        "열린 포트가 공격 대상 목록에 올랐습니다.",
        ["보안그룹에서 불필요한 공개 포트 닫기"],
        "investigate", "SEC-01"),
    "Recon:EC2/Portscan": _e(
        "인스턴스가 포트 스캔 수행",
        "이 인스턴스가 다른 호스트로 포트 스캔을 보내고 있습니다.",
        "침해된 인스턴스가 내부 정찰에 쓰이고 있을 수 있습니다.",
        ["승인된 공격 실습 인스턴스인지 확인", "아니면 인스턴스 격리(보안그룹 교체)·조사"],
        "investigate"),
    "UnauthorizedAccess:IAMUser/InstanceCredentialExfiltration.OutsideAWS": _e(
        "EC2 역할 자격 증명이 AWS 밖에서 사용됨",
        "인스턴스 역할의 임시 자격 증명이 외부 IP 에서 쓰였습니다.",
        "인스턴스가 침해되어 자격 증명이 유출됐을 가능성이 큽니다.",
        ["역할의 활성 세션 무효화 (IAM > 역할 > 세션 취소)", "인스턴스 격리·조사, IMDSv2 강제 확인"],
        "investigate", "SEC-05",
        note="임시 자격 증명(ASIA…)은 액세스 키 비활성화 대상이 아니어서 자동 키 비활성화가 실패할 수 있습니다."),
    "UnauthorizedAccess:IAMUser/InstanceCredentialExfiltration.InsideAWS": _e(
        "EC2 역할 자격 증명이 다른 AWS 계정에서 사용됨",
        "인스턴스 역할의 임시 자격 증명이 다른 AWS 계정의 자원에서 쓰였습니다.",
        "인스턴스가 침해되어 자격 증명이 유출됐을 가능성이 큽니다.",
        ["역할의 활성 세션 무효화 (IAM > 역할 > 세션 취소)", "인스턴스 격리·조사"],
        "investigate", "SEC-05",
        note="임시 자격 증명(ASIA…)은 액세스 키 비활성화 대상이 아니어서 자동 키 비활성화가 실패할 수 있습니다."),
    "UnauthorizedAccess:IAMUser/MaliciousIPCaller": _e(
        "알려진 악성 IP 에서 API 호출",
        "위협 목록에 있는 IP 에서 이 자격 증명으로 AWS API 가 호출됐습니다.",
        "자격 증명이 유출돼 공격자가 쓰고 있을 수 있습니다.",
        ["해당 액세스 키 비활성화", "CloudTrail 로 호출 내역 확인 후 키 교체"],
        "investigate", "SEC-05"),
    "CredentialAccess:IAMUser/AnomalousBehavior": _e(
        "비정상적인 자격 증명 접근 API 호출",
        "평소와 다른 방식으로 비밀·자격 증명 관련 API(GetSecretValue 등)가 호출됐습니다.",
        "탈취한 자격 증명으로 더 많은 비밀을 모으는 중일 수 있습니다.",
        ["해당 액세스 키 비활성화", "CloudTrail 로 호출 내역 확인"],
        "investigate", "SEC-05"),
    "Discovery:IAMUser/AnomalousBehavior": _e(
        "비정상적인 정보 수집 API 호출",
        "평소와 다른 방식으로 목록 조회(List·Describe) API 가 호출됐습니다.",
        "공격 전에 계정 구조를 파악하는 정찰일 수 있습니다.",
        ["해당 액세스 키 비활성화", "CloudTrail 로 호출 내역 확인"],
        "investigate", "SEC-05"),
    "Policy:IAMUser/RootCredentialUsage": _e(
        "루트 계정 자격 증명 사용",
        "루트 사용자로 API 가 호출됐습니다.",
        "루트는 권한을 제한할 수 없어 사고가 나면 피해가 가장 큽니다.",
        ["루트를 쓴 이유 확인, 일상 작업은 IAM 사용자·역할로", "루트 MFA 확인"],
        "investigate"),
    "Stealth:IAMUser/CloudTrailLoggingDisabled": _e(
        "CloudTrail 로깅 중지",
        "CloudTrail 추적이 중지되거나 삭제됐습니다.",
        "공격자가 흔적을 지우려는 행동일 수 있습니다.",
        ["추적 다시 켜기 (Terraform apply)", "CloudTrail 기록에서 중지한 주체 확인"],
        "investigate", "SEC-09"),
    "PenTest:IAMUser/KaliLinux": _e(
        "침투 테스트용 OS(Kali)에서 API 호출",
        "Kali Linux 에서 이 자격 증명으로 AWS API 가 호출됐습니다.",
        "승인되지 않았다면 자격 증명이 공격 도구에서 쓰이고 있습니다.",
        ["승인된 실습인지 확인, 아니면 키 비활성화"],
        "investigate"),
    "CryptoCurrency:EC2/BitcoinTool.B!DNS": _e(
        "암호화폐 채굴 관련 도메인 조회",
        "인스턴스가 암호화폐 채굴 관련 도메인을 조회했습니다.",
        "인스턴스가 침해되어 채굴에 쓰이고 있을 수 있습니다.",
        ["인스턴스 격리·조사, 필요하면 새로 구축"],
        "investigate"),
    "Backdoor:EC2/C&CActivity.B!DNS": _e(
        "명령·제어(C&C) 서버 도메인 조회",
        "인스턴스가 알려진 C&C 서버 도메인을 조회했습니다.",
        "악성코드에 감염되어 원격 조종당하고 있을 수 있습니다.",
        ["인스턴스 격리·조사, 필요하면 새로 구축"],
        "investigate"),
}

# 표에 없는 GuardDuty 유형 — 유형 앞부분(위협 목적)으로 공통 설명을 만든다.
FAMILIES = {
    "Recon": "정찰(스캔·탐색)", "UnauthorizedAccess": "무단 접근 시도", "CredentialAccess": "자격 증명 탈취 시도",
    "Discovery": "정보 수집(정찰) API 호출", "Impact": "자원 악용·파괴 행위", "Backdoor": "백도어·원격 조종 징후",
    "CryptoCurrency": "암호화폐 채굴 징후", "Trojan": "트로이목마 징후", "Stealth": "흔적 숨기기",
    "PenTest": "침투 테스트 도구 사용", "Policy": "보안 정책 위반", "Persistence": "지속성 확보 시도",
    "PrivilegeEscalation": "권한 상승 시도", "Exfiltration": "데이터 유출 징후", "Execution": "악성 실행 징후",
    "DefenseEvasion": "탐지 회피 시도", "InitialAccess": "초기 침투 시도",
}


def family_entry(family):
    label = FAMILIES.get(family)
    if not label:
        return None
    return _e(f"GuardDuty 위협 탐지 — {label}",
              f"GuardDuty 가 {label} 행위를 탐지했습니다.",
              "공격이 진행 중이거나 자원이 이미 침해됐을 수 있습니다.",
              ["탐지 대상 자원과 출발지 IP 확인", "AWS 원문 설명과 조치 안내 확인"],
              "investigate")


OTHERS = {
    # 이 프로젝트 Config 규칙 4개 (modules/security/config.tf). Config finding 제목 = 규칙 이름.
    "config:restricted-ssh": _e(
        "SSH(22) 전체 공개 보안그룹 (Config)",
        "보안그룹이 0.0.0.0/0 에서 22번을 허용합니다.",
        "SSH 무차별 대입 대상이 됩니다. 이 규칙은 설정 점검이며 공격 탐지가 아닙니다.",
        ["22번 공개 규칙 삭제, 접속은 SSM Session Manager 사용"],
        "sg", "SEC-01"),
    "config:restricted-common-ports": _e(
        "위험 포트(22·3306·3389·23) 전체 공개 (Config)",
        "보안그룹이 0.0.0.0/0 에서 22·3306·3389·23 중 하나를 허용합니다.",
        "DB·원격 접속 포트가 인터넷에 노출됩니다.",
        ["공개 규칙 삭제, DB 포트는 앱 서버 보안그룹에서만 허용"],
        "sg", "SEC-03",
        note="AutoRemediation=enabled 태그가 있는 보안그룹(db-auto-sg)만 자동 회수하고, 태그 없는 db-manual-sg 는 대조군으로 수동 처리합니다."),
    "config:iam-no-full-admin": _e(
        "관리자 전체 권한 정책 (Config)",
        "IAM 정책에 Action \"*\" · Resource \"*\" 허용 문장이 있습니다.",
        "이 정책이 붙은 주체가 탈취되면 계정 전체가 넘어갑니다.",
        ["필요한 작업·자원만 허용하도록 정책 축소"],
        "iam", "SEC-05"),
    "config:cloudtrail-enabled": _e(
        "CloudTrail 꺼짐 (Config)",
        "계정에 활성화된 CloudTrail 추적이 없습니다.",
        "API 호출 기록이 남지 않아 사고 조사를 할 수 없습니다.",
        ["CloudTrail 추적 다시 켜기 (Terraform apply)"],
        "terraform", "SEC-09"),
    "waf:soar-waf-alarm": _e(
        "WAF 차단 급증",
        "WAF 가 1분 동안 임계치 이상의 요청을 차단했습니다.",
        "웹 공격(SQL 인젝션·XSS·요청 폭주)이 들어오고 있습니다. 차단은 동작 중입니다.",
        ["WAF 샘플 요청에서 출발지 IP·공격 유형 확인", "공격이 계속되면 IP 차단 규칙·요청 수 제한 강화"],
        "investigate", "SEC-08"),
    "product:IAM Access Analyzer": _e(
        "외부 접근이 허용된 자원",
        "자원 정책이 다른 계정이나 공개 접근을 허용합니다.",
        "의도하지 않은 외부 주체가 자원에 접근할 수 있습니다.",
        ["정책의 Principal 확인 — 의도한 접근이면 보관(archive), 아니면 정책 수정"],
        "iam", "SEC-05"),
}

# 자동 조치 기록의 규칙 토큰(SEC-06A·SEC-06B·HONEYPOT, 해제 UNBLOCK-*) — 조치 이력 제목용.
BRUTEFORCE = {
    "SEC-06A": "MySQL 무차별 대입 → 공격 IP NACL 차단",
    "SEC-06B": "SSH 접속 시도 거부 급증(Flow Logs) → 공격 IP NACL 차단",
    "HONEYPOT": "미끼서버 접속 → 공격 IP NACL 차단",
    "UNBLOCK-MANUAL": "차단 IP 오탐 해제(NACL Deny 삭제)",
    "UNBLOCK-EXPIRY": "차단 기간 만료 → NACL Deny 해제",
}
