import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {ROOT, until, makeFetchMock, appDOM} from './dom-test-support.mjs';

test('canonical events, vulnerabilities, history and actual incident data render without legacy requests',async t=>{
 const network=makeFetchMock(),iso=new Date().toISOString();
 network.respond('/api/history',{data:{items:[],jobs:[{jobId:'job-1',eventId:'EVT-0003',status:'RUNNING',error:null,createdAt:iso}],nextCursor:null},meta:{schemaVersion:'1',asOf:iso}});
 const {dom,$,click,errors}=appDOM(network);t.after(()=>dom.window.close());
 await import(pathToFileURL(path.join(ROOT,'static/js/app.js')).href);
 await until(()=>$('#content').textContent.includes('Contract test event'),'event did not render');
 assert.equal($('#data-mode').textContent,'실데이터');
 click('nav [data-view="events"]');
 await until(()=>$('#content .event-link'));
 click('#content .event-link');
 await until(()=>$('#event-dialog').open&&$('#dialog-content').textContent.includes('i-fixture'));
 assert($('#dialog-content').textContent.includes('표준 이벤트 API'));
 assert.equal($('#dialog-content').querySelector('[data-action="approve"]'),null);
 click('#dialog-content [data-action="close"]');
 click('nav [data-view="vulnerabilities"]');
 await until(()=>$('#vulns')?.textContent.includes('CVE-2026-0001'),'vulnerability view did not render');
 assert($('#vulns').textContent.includes('Inspector'));
 click('nav [data-view="incidents"]');
 await until(()=>$('#incidents')?.textContent.includes('SECURITY_HUB'));
 assert($('#incidents').textContent.includes('표준 API에서 제공되지 않습니다'));
 click('nav [data-view="responses"]');
 await until(()=>$('#audit-log')?.textContent.includes('기록된 조치가 없습니다'));
 assert($('#audit-log').textContent.includes('job-1'));
 assert($('#audit-log').textContent.includes('RUNNING'));
 assert(network.calls.some(call=>call.pathname==='/api/history'));
 assert(network.calls.every(call=>!call.pathname.startsWith('/api/legacy/')));
 assert.deepEqual(errors,[]);
});
