const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('assert/strict'),fs=require('fs'),path=require('path');
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const p=await browser.newPage({viewport:{width:1440,height:900},reducedMotion:'reduce'});const errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto('http://127.0.0.1:5000/');await p.waitForSelector('.attack-connection');await p.waitForFunction(()=>document.querySelector('#load-state').hidden);
 assert.equal(await p.locator('#markers .marker').count(),17);assert.equal(await p.locator('#region option').count(),19);
 const ids=await p.locator('#markers .marker').evaluateAll(es=>es.map(e=>e.dataset.region));assert.equal(new Set(ids).size,17);
 for(const id of ids){await p.locator('#region').selectOption(id);assert((await p.locator('#region-panel').innerText()).includes(id));}
 await p.locator('#region').selectOption('ap-northeast-2');await p.locator('#zoom-reset').click();
 assert.equal(await p.locator('.attack-connection').count(),1);assert.match(await p.locator('#attack-summary').innerText(),/위치 미상 1건/);
 await p.locator('#attack-filter').selectOption('EVT-0013');assert.equal(await p.locator('.attack-connection').count(),0);await p.locator('#attack-filter').selectOption('EVT-0005');assert.equal(await p.locator('.attack-connection').count(),1);
 // Both ends must use exactly the same projection as region markers.
 const endpoints=await p.evaluate(()=>{const path=document.querySelector('.attack-line'),end=path.getPointAtLength(path.getTotalLength()),marker=document.querySelector('#markers [data-region="ap-northeast-2"]');return {x:end.x,y:end.y,mx:marker.transform.baseVal.getItem(0).matrix.e,my:marker.transform.baseVal.getItem(0).matrix.f};});assert(Math.abs(endpoints.x-endpoints.mx)<.1&&Math.abs(endpoints.y-endpoints.my)<.1);
 await p.locator('.attack-connection').focus();await p.keyboard.press('Enter');assert.match(await p.locator('.attack-detail').innerText(),/203.0.113.21/);assert.match(await p.locator('.attack-detail').innerText(),/모의 위치/);await p.keyboard.press('Escape');
 await p.locator('#source').selectOption('Config');assert.equal(await p.locator('.attack-connection').count(),0);await p.locator('#clear-filters').click();
 await p.locator('#search').fill('EVT-0013');await p.locator('tbody [data-event]').click();assert.match(await p.locator('.attack-detail').innerText(),/위치 미상/);await p.keyboard.press('Escape');
 await p.locator('#clear-filters').click();await p.locator('[data-hours="168"]').click();await p.locator('#search').fill('10.0.0.8');await p.locator('tbody [data-event]').click();assert.match(await p.locator('.attack-detail').innerText(),/사설 IP/);await p.keyboard.press('Escape');assert.equal(await p.locator('.attack-connection').count(),0);await p.locator('#clear-filters').click();
 const box=await p.locator('#world-map').boundingBox();const px=box.x+box.width*.55,py=box.y+box.height*.62;
 await p.mouse.move(px,py);const scroll=await p.evaluate(()=>scrollY);await p.mouse.wheel(0,-500);await p.waitForFunction(()=>Number(document.querySelector('#world-map').dataset.zoom)>1.8);assert.equal(await p.evaluate(()=>scrollY),scroll);
 const before=await p.locator('#map-transform').getAttribute('style');await p.mouse.move(px,py);await p.mouse.down();await p.mouse.move(px+85,py+25,{steps:8});await p.mouse.up();assert.notEqual(await p.locator('#map-transform').getAttribute('style'),before);assert.equal(await p.locator('#event-dialog').isVisible(),false);
 await p.mouse.wheel(0,-10000);await p.waitForFunction(()=>document.querySelector('#world-map').dataset.zoom==='4.00');await p.mouse.wheel(0,10000);await p.waitForFunction(()=>document.querySelector('#world-map').dataset.zoom==='1.00');
 await p.locator('#zoom-in').click();const kb=await p.locator('#map-transform').getAttribute('style');await p.locator('#world-map').focus();await p.keyboard.press('ArrowRight');assert.notEqual(await p.locator('#map-transform').getAttribute('style'),kb);await p.locator('#zoom-reset').click();assert.match(await p.locator('#map-transform').getAttribute('style'),/translate\(0px,\s*0px\) scale\(1\)/);
 await p.locator('#region').selectOption('all');assert((await p.locator('.attack-connection').count())>10);await p.locator('#region').selectOption('global');assert.equal(await p.locator('.attack-connection').count(),0);
 await p.locator('#region').selectOption('ap-northeast-2');await p.locator('#zoom-reset').click();await p.waitForFunction(()=>document.querySelector('#toast').hidden);
 const out=path.resolve(__dirname,'../screenshots/v2');fs.mkdirSync(out,{recursive:true});await p.screenshot({path:path.join(out,'overview-1440.png'),fullPage:true});await p.setViewportSize({width:1920,height:1080});await p.screenshot({path:path.join(out,'overview-1920.png'),fullPage:true});await p.setViewportSize({width:390,height:844});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.screenshot({path:path.join(out,'overview-mobile.png'),fullPage:true});
 await p.emulateMedia({reducedMotion:'no-preference'});assert.equal(await p.locator('.attack-motion').first().evaluate(e=>getComputedStyle(e).animationName),'attack-flow');await p.emulateMedia({reducedMotion:'reduce'});assert.equal(await p.locator('.attack-motion').first().evaluate(e=>getComputedStyle(e).animationName),'none');
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'verification.json'),JSON.stringify({passed:true,regions:17,checks:['all region choices','flow count and filtering','shared endpoint projection','IP event details','unknown and private IP excluded','wheel zoom bounds','no page scroll on map wheel','drag without click','arrow-key pan','reset','global excluded','1440 / 1920 / 390 layouts','reduced motion'],errors},null,2));await browser.close();console.log('PASS: v2 map and attack-flow checks');
})().catch(e=>{console.error(e);process.exit(1)});


